# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4679402d02656a8f3c4c8841df1bebad9446c065a175617492e569ef108b5abbc3d2d09736271b93b9f45d0e53ff67a3458354369534b6208c71463618fd1568

test:
  secret_key_base: 575a0dbd29bb607b40f8a7dc6d06a234e411713f5d6ed312bbfa9203257dd1d76db5200be00f63e32a0c7eb5c85f9bdb73dd37638bd13ee6d7dd32ce2caf2045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
